### ISSUE TITLE
Suggestion: Multiplayer initiative hiding

### ISSUE THREAD

**Issue by benbaker100** [Lurkars/gloomhavensecretary#10]
In the original Gloomhaven Helper, when multiple devices were connected to the same server, at the start of the round when putting in initiative numbers, they would show up as ?? on the other devices. This avoided showing other players my initiative before they finished choosing their cards. The ?? changed to the actual number when the draw button was pushed. Would it be difficult to implement that here?

![image](https://user-images.githubusercontent.com/81772678/179451917-1cfe5a58-2512-421a-acf5-96aae24abddc.png)
![image](https://user-images.githubusercontent.com/81772678/179451986-0747f314-9ed6-47ed-869f-40b6cd95d1a1.png)

PS Thanks for the great app!

**Comment by Lurkars** [comment]
Yes this is definitely on the agenda for the server part. Also I want to add something like a right management. With that I mean, that certain clients can only change specific things, for example only update their own character.

**Comment by benbaker100** [comment]
That was quick, well done! Looks like it's working perfectly. Thank you so much!
