### ISSUE TITLE
Saving and loading game and setting files on iPad

### ISSUE THREAD

**Issue by bstlaurentnz** [Lurkars/gloomhavensecretary#11]
playing off the ghs.champonthis.de site, i can successfully use all features on the latest ipadOS 15.5.

The only issue I've hit is that when you go to save settings, the ghs.json file is marked as a text file, so ipadOS automatically appends .txt to the end of it (mimetype set maybe?)

Then, when you go to load said file, you can't select it, likely because GHS is expecting a .json file and refuses to open the gsh.json.txt file. 

Any chance either: 
mimetype / filetype can be set properly on download, 
load file can also load .txt files and attempt to treat them as .json files?

Otherwise, using this on an ipad is a GREAT experience.

**Comment by Lurkars** [comment]
Yes, there is really i mimetype of plain/text set. I will change and then please test again.

**Comment by Lurkars** [comment]
I changed mimetype with https://github.com/Lurkars/gloomhavensecretary/commit/879190ceae6c40cd427a3c2b57f66abca205ae6a please test with v0.10.1 and close issue if resolved.

**Comment by bstlaurentnz** [comment]
I'm assuming you've pushed it to the live site? I just tested and it's now working as expected :) THANKS!
