### ISSUE TITLE
Applying wound

### ISSUE THREAD

**Issue by connor2k** [Lurkars/gloomhavensecretary#12]
Scenario: serving from windows desktop. Using iphone and ipads to access.
Apply wound to creature. Symbol keeps popping up over and over, effectively spamming it and not allowing you to do any other actions.

**Comment by Lurkars** [comment]
Can you provide versions used and what you're doing exactly that caused this?

**Comment by connor2k** [comment]
I was using version 0.9.7. I just updated to version 0.10 today and will try again. 

I would mark a creature as wounded. And then when getting to their turn it would pop up the symbol for wounded repeatedly.

**Comment by Lurkars** [comment]
Okay thanks. Then please close this issue if you finished testing and issue is resolved! The automatic applying of conditions was very buggy in first iterations. So hopefully just working in latest release.
