### ISSUE TITLE
'Attack Bonus' actions ambiguously look the same as 'Attack' actions

### ISSUE THREAD

**Issue by atrest1** [Lurkars/gloomhavensecretary#13]
Monster ability cards can have a conditional attack bonus, for example the JOTL Zealot card 'Vile Scourge', which can use the Wind element to add +1 to the attack (card screenshot here: https://tabletopwanderers.com/gloomhaven-jaws-of-the-lion-zealot-overview-strategy-guide/).

Currently, the abilities data model doesn't support attack bonuses, so they confusingly look exactly the same as an attack action.
Where the current card looks like the below, implying a second attack:
![image](https://user-images.githubusercontent.com/50980680/184052861-851869d5-df0d-4de3-9f9e-815cfe09af34.png)
The card should look like this instead, indicating a modification to the above attack action:
![image](https://user-images.githubusercontent.com/50980680/184053520-9d874c3f-c349-462d-b314-1c847e774642.png)

The same issue occurs with range bonuses, such as the JOTL Zealot card 'Boil Blood', which can use the Fire element to add +2 to the range.

If no change is made, it's still possible to distinguish between an attack bonus or a new attack action, due to the absence of a divider on the card, but it's a subtle difference.

Not sure how this should interact with the 'Show Calculated Stats' feature, it should probably just be excluded from calculation.

**Comment by Lurkars** [comment]
Thanks for the report! Very important to me! I will take a look, which ability cards are affected and fix this!

**Comment by Lurkars** [comment]
I found some more ability cards, hopefully I found all. So should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/c51255f5f1695ebf49c69dfb7bdf7846374116e6 in https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.12.2

Please verify and close issue.

**Comment by atrest1** [comment]
Looks great, thank you!
