### ISSUE TITLE
JOTL monster deck bugs

### ISSUE THREAD

**Issue by atrest1** [Lurkars/gloomhavensecretary#14]
I took a look at all monster deck cards for JOTL to compare them to my set, and discovered a few issues.

1. Black Sludge card 433 - The Push and Poison effects are a single action, not multiple. The is incorrect because the 'Target all adjacent enemies' instruction should apply to both the Push and the Poison.
 Incorrect: 
 ![image](https://user-images.githubusercontent.com/50980680/184260892-6cbb90fc-63fd-48db-89ff-05f49cd68b68.png)
 Correct:
 ![image](https://user-images.githubusercontent.com/50980680/184260950-ca27241e-95bc-47b1-8c57-6a00b37188b9.png)
2. Vermling Scout card 463 - The Attack effect incorrectly specifies target: 2, which does not match my physical copy.
 Incorrect:
 ![image](https://user-images.githubusercontent.com/50980680/184261127-f3e8fa64-b965-4682-ae35-27118ea380dc.png)
 Correct:
 ![image](https://user-images.githubusercontent.com/50980680/184261072-ff43f069-593a-45e3-9f16-a00e20a3d801.png)
3. General jump value bug: When Jump is a subaction of a move action, it's rendered with a value '-', which shouldn't be there. Not a big deal.
![image](https://user-images.githubusercontent.com/50980680/184259321-1b09153c-4288-4774-9ce7-549d4f972dd6.png)
4. General divider bug: I don't think the divider placement can be inferred in actions.html, I think it needs to be explicitly defined in the card data model (maybe by always putting a divider between each action and using subactions?). I noticed this issue with the following cards: 
   - Chaos Demon card 415: Shield action should occur separately after the attack, not during. (Could be an important difference if there are any counterattack effects?)
    Incorrect:
   ![image](https://user-images.githubusercontent.com/50980680/184261229-db09eb1e-1a33-4b8c-855e-ac3cc2d8dffd.png)
   Correct:
   ![image](https://user-images.githubusercontent.com/50980680/184261280-bade61bf-4c03-4caa-8e5f-4964cefa310e.png)
   - Chaos Demon card 416: Heal action should occur separately after the attack, not during. I don't think anyone will interpret this incorrectly though.

Other than the above issues, I've verified every card in the monster deck is the same as my physical copy for JOTL.

**Comment by atrest1** [comment]
I've created a PR for all but the 'divider' issue.

**Comment by Lurkars** [comment]
Thank you very much! A take a look at the PR. I think the divider is a real issue. For now, it's hard coded to not show divider on element action. I think this come from element infusion, because it's never bound to an action in my understanding (so element ja always infused). The consumption side is the problem and in that case the Base GH decks, because there is no separator on the cards. So easy fix is to just show divider also on element (maybe still hide for infusion?! I think there is also no separator on JOTL's cards!?) and put consumption into subaction where required. The only problem may become the migration of base GH data, because I am unsure if it is visible on the card. Best approach can be a logical stuff, because consumption triggering range or target for example won't make sense as separate action, where attack, heal or shield does. First of all I will fix the separator issue and than take a look at all cards.

**Comment by atrest1** [comment]
You're right, I never noticed that GH does not have separators, while JOTL does.
I also agree with you about element infusion - my understanding is that having a separator or not doesn't matter for infusion because the infusion can't be used during the current turn anyway. I don't think there are separators before any infusions in JOTL, but there are sometimes separators before element consumption.

I'd be tempted to fix this by:
- Changing the separator logic so that a separator is always visible between each action (except infusions?).
- Make every element consumption action a sub-action of the previous action (after these first two steps, the cards should look the same as before any changes were made).
- Then, look at every card to determine whether the element action needs to be made a stand-alone separate action. (I think this is only the two cards mentioned above for JOTL).
This approach gives more flexibility in case there are unexpected cards later.

Alternatively it might be possible to tweak the rules so that the divider is only hidden if the action is a modification on the previous action (add infusion, add value to attack or range or move, etc) - I'm just not sure if that rule holds for all games. For example, I could imagine that while the JOTL card 415 (image above) has a shield as a separate action, maybe there is a card in another game which adds the shield as part of the attack action, which could have an effect. There might also be cards which have just a text description of what the element consumption does, so it'll be difficult to infer automatically whether this is a modification to the previous action or not.

**Comment by Lurkars** [comment]
I think I fixed all this stuff with https://github.com/Lurkars/gloomhavensecretary/commit/73ae762123528d49b4483fb16fc1880174c939a3 Please check out latest release. I got trough the decks of other editions and I think I could spot a difference on the base GH cards where consumption is seperate or not. On other editions it was also visible on cards (by any2cards), so there were also some mistakes fixed now.

**Comment by atrest1** [comment]
I've confirmed that the latest commit has fixed these issues, thank you!
