### ISSUE TITLE
[bug] Ancient Artillery missing Range on attack

### ISSUE THREAD

**Issue by TylerHelmuth** [Lurkars/gloomhavensecretary#16]
Ran into what I think was a bug yesterday while using Gloomhaven Secretary's public website and server.  

During scenario 8 in Crimson Scales the ancient artillery pulled card 707 which should use the monster's base range, but the base range was not added to the card (we were using `Show calculated stats` and `Add stat values to abilities`) and  the monster's stat block was not showing its base range.

<img width="1465" alt="Screen Shot 2022-08-12 at 8 39 47 PM" src="https://user-images.githubusercontent.com/12352919/184503881-03831cea-369d-44a6-bc42-21df20944eaf.png">

**Comment by TylerHelmuth** [comment]
Playing around some more this morning it looks like maybe the ancient artillery is always missing its range stat in the state block

<img width="1908" alt="image" src="https://user-images.githubusercontent.com/12352919/184504302-b74631f5-14bb-4d3c-92f1-79e3126e5f77.png">

**Comment by Lurkars** [comment]
This is a weird bug. Stats data is there, but isn't shown. Have to take a deeper look, bit I can reproduce and will check soon! Just compared with bandit archer for example which is shown correctly besides I can spot no obvious difference in monster stats between them.

**Comment by TylerHelmuth** [comment]
Ya I've been reading through the data and code and can't find the root cause yet.  I _think_ the issue is related to the fact that the monster has no movement.  I can reproduce the error with a deep terror as well

<img width="1804" alt="image" src="https://user-images.githubusercontent.com/12352919/184505460-f1223016-ec6a-4be1-bcbb-db0339efc1b6.png">

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/12352919/184505496-59c6cb7a-5b58-4569-85e6-cfb9e7255fb0.png">

**Comment by TylerHelmuth** [comment]
Looks like that deep terror is missing its range and attack

**Comment by Lurkars** [comment]
Ah yes, that's the hint. It's not missing, the value "-" for movement is missing and therefore the range value is shown next to movement. This must be related to the fix of "jump" showing a value. I will fix it. So other issue is, why range stat isn't shown on ability card with "stats values on ability cards". I'll take a look, but I thinks it's related to the area attack, have to do more complex check if area contains a gray field, so it's melee and range ignored (which is not the case on ancient artillery!).

**Comment by Lurkars** [comment]
should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/45ae331db68c44c7f28656ead76c2521841a5684 in [v0.12.4](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.12.4). Please verify and close.

**Comment by TylerHelmuth** [comment]
Everything looks good, thanks!
