### ISSUE TITLE
When playing with a game of 3 devices, the perks disappear.

### ISSUE THREAD

**Issue by hg2022YIPPY** [Lurkars/gloomhavensecretary#17]
We noticed when trying to update the character sheet, items would reset to default.

This is an AMAZING APP!!!

**Comment by Lurkars** [comment]
Thanks. Found the issues, will update fix soon. Also find some issues with the perks.

**Comment by Lurkars** [comment]
should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/6409aced6d693b83d71de1a7c64d2bf558afb899 ([v0.13.1](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.13.0). Please verify and close issue.

**Comment by hg2022YIPPY** [comment]
Seems to be fixed, man that was fast. GREAT JOB!!!

**Comment by hg2022YIPPY** [comment]
closing ticket
