### ISSUE TITLE
Adding ability to change Monster Picture

### ISSUE THREAD

**Issue by hg2022YIPPY** [Lurkars/gloomhavensecretary#18]
Occasionally, I like to print 3D monsters. But the 3D printed water demon doesn't look anything like the default GH water demon picture. I would like to upload a picture of my 3d printer monsters into your application to replace the default monster picture with the 3D printer Monster. 

As a second idea, I would also like the ability to modify the attack cards to add\del or modify the information to better fit my adventure. It is like adding the stickers on the characters attack cards

**Comment by Lurkars** [comment]
You are able to set your own edition data in the Data Management section. Therefor you will need a JSON file with the corresponding data behind some URL to load from. So this is not easy, but possible. Only change I will made for now is adding a replace field. So you can copy existing monster/character and override it. So in you example you would copy the water demon data and just add "thumbnailUrl" with url to picture and replace to true.

After update, I will document it in detail here, how you can do it.

**Comment by hg2022YIPPY** [comment]
That sounds awesome, Thanks

Sam

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Lurkars** [comment]
I will write documentation next days. It should be possible to just put this stuff on github pages, but I need to verify first. At least it would become a bit easier than requiring another webserver. (@hg2022YIPPY  Please check you last comment, you have some Mail meta in it, could be removed!)

**Comment by Lurkars** [comment]
Okay, I just checked it with a little Demo:
Repository https://github.com/Lurkars/ghs-custom-demo
Published via GitHub Pages on https://lurkars.github.io/ghs-custom-demo/

So,afterwards in GHS I go to Data Management and add https://lurkars.github.io/ghs-custom-demo/custom-demo.json as Edition Data URL. Afterwards I have my custom edition data available.

In your case now, you would add an Edition Data File with just one monster set, copy the monster data from (I am now confused you said "Water Demon", maybe you mean "Wind Demon?): https://github.com/Lurkars/gloomhavensecretary/blob/main/data/gh/monster/wind-demon.json and add following properties:
```
      "replace": true,
      "thumbnailUrl": "${url to your image (also on GitHub pages)}",
```

For example: https://lurkars.github.io/ghs-custom-demo/replace.json 

I hope this is enough info for you to deploy your own data via GitHub Pages and include in your client(s). If you still need help, you can reopen this issue. For now the editor for creating such JSON files in with an UI is low priority, so you have to create those files by hand now.

**Comment by hg2022YIPPY** [comment]
How do I go about adding a new thumbnailurl to every default GH Monster?

**Comment by Lurkars** [comment]
> How do I go about adding a new thumbnailurl to every default GH Monster?

Haha okay. With this approach, you would need to copy every monster and change it. But I think, if you really want to customize GHS that much, that you should host/run your own version and just replace all images to your needs (monster images are under `assets/images/monster/thumbnail`). To do so you have a few option. Obviously you can also use GitHub pages and create a repository with the complete GHS build. Alternatively you just fork this repository and use the GitHub workflow already provided to automatically publish to GitHub pages. 

Second option is easiest, if you're not required to have the instance public available (you also can, but requires a bit more). You download and run GHS server component and serve the client with it, see https://github.com/Lurkars/ghs-server#serve-client. Afterwards change the images in `<your-home-folder>/.ghs/gloomhavensecretary` to your needs.
