### ISSUE TITLE
Automatic Apply Conditions

### ISSUE THREAD

**Issue by crabcrouton** [Lurkars/gloomhavensecretary#19]
Hi there,

The Automatic Apply Conditions function broke recently.

When it is a figure's turn, and they receive Wound, at the end of their turn the app applies the Wound damage immediately.
Seems to also occur with Regen.

Tested on the web app.

Thanks,

**Comment by Lurkars** [comment]
Should hopefully be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/2470357cef4f9d48f7389b53576ab379bc0ac0bb. Please test with [v0.17.3](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.17.3) and close issue if resolved.
