### ISSUE TITLE
Gold Conversion values off for some Levels

### ISSUE THREAD

**Issue by jgwehr** [Lurkars/gloomhavensecretary#2]
Hey! I noticed the **Gold Conversion** numbers were off in the app. I think it's related to the math here:
https://github.com/Lurkars/gloomhavensecretary/blob/f8a4b2852b6b2935fb8a6ebaefd282198849549b/src/app/ui/footer/level/level.ts#L27
![image](https://user-images.githubusercontent.com/13216529/175580035-63674850-e400-4335-a69d-d8827199ecf4.png)

You can get a little closer with an approach like this (you probably have a better idea, though!):

```javascript
this.loot = Math.floor(2 + gameManager.game.level / 2)
if (gameManager.game.level > 6) {
  this.loot = 6;
}
```

**Comment by jgwehr** [comment]
On second check, I also noticed the multipliers act a little funky in general. 

1. My characters are level 5 and 6, for a default level 3
1. If I set the scenario level to any other value, the multipliers adjust. _level 6, trap=6, xp=16, gold=*5_
1. If I refresh the page, the level is set is retained. However, the multiplier values rest to my "default level". _level 6, trap=3, xp=6, gold=*3_

**Comment by Lurkars** [comment]
Thanks for the report. Should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/63a3dd05bdb6293242d8d9d80bccf138a11ec630 (Version 0.7.1).
