### ISSUE TITLE
Not enough Perks

### ISSUE THREAD

**Issue by hg2022YIPPY** [Lurkars/gloomhavensecretary#20]
When a player is at max level and all of the battle goals have been achieved. We are one short from selecting all of the perks.

**Comment by Lurkars** [comment]
With 8 Level and 6 checks you can have 14/15 perks (works as designed). Additional perks can be gained with additional retirements. This can be set in bottom of character sheet. 

If you want to apply why house rule to gain more perks than usual, I implement a workaround: double click on a work to ignore disabled perks.

**Comment by hg2022YIPPY** [comment]
Now we are not able to select perk normally.
