### ISSUE TITLE
Enhancement: manage multiple parties

### ISSUE THREAD

**Issue by rbeumer** [Lurkars/gloomhavensecretary#22]
We are playing GH with a party of four and JOTL with just the two of us. It would be really nice to be able to switch between parties/profiles in the app.

**Comment by Lurkars** [comment]
I will think about this. 

Meanwhile I have at least two workarounds for you:
- under "Data Management" you can export and import your game to a file. So after ending your session, just export game state and before import it
- use the server function and create two games with two different passwords and change password according to your session

**Comment by Lurkars** [comment]
Multiple party support is now possible on the party sheet with https://github.com/Lurkars/gloomhavensecretary/commit/0b2cf8c5ded8c330e87fb64c9eecf66d513c40ba ([v0.19.0](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.19.0)). You can add, remove and change the current party. For not changing during scenario, this is only possible when no scenario is running (end current scenario by clicking on it's name on the bottom and finish or cancel scenario). Happy about feedback.

**Comment by rbeumer** [comment]
It works very well for us, thanks!
