### ISSUE TITLE
Issue with objects HP only increasing when swiping

### ISSUE THREAD

**Issue by rbeumer** [Lurkars/gloomhavensecretary#26]
We were playing scenario 29 (Sanctuary of Gloom) where you have several objects that you need to destroy by attacking. When you swipe to the left on the card for the object it's HP only seems to increase, looks like a bug to me.

**Comment by Lurkars** [comment]
Thank you, I will take a look.

**Comment by Lurkars** [comment]
Should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/454e39f6c557d4f0c6303b992144eb059a611b82 in [v0.18.4](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.18.4). Please test with latest version and report back. Thank you.

**Comment by rbeumer** [comment]
It seems to be working, thanks!
