### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by imdudgh** [Lurkars/gloomhavensecretary#3]
I found that the name of the Valrath woman had a typo:

https://github.com/Lurkars/gloomhavensecretary/blob/c2b4160c7a9d8997aef1397916d296a33252a152/data/gh/label.json#L235

**Comment by Lurkars** [comment]
Thank. Should be fixed in https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.8.0
