### ISSUE TITLE
Responsive support for multiple columns

### ISSUE THREAD

**Issue by cerealcable** [Lurkars/gloomhavensecretary#30]
I am interested in adding support for multiple columns (my gaming group really prefers to see all of the monsters), preferably automatically happening if the zoom level supports room for multiple columns similar to how ghh previously worked. Would you prefer this feature just happen or should I add a configuration element in the settings menu for this support?

Great work on Gloomhaven Secretary! Our game group recently started using this and we are quite excited about it so great work and it's having a great impact on our groups enjoyment of the game!

**Comment by Lurkars** [comment]
This is already implemented! Please try out zooming out!

**Comment by cerealcable** [comment]
I definitely confirmed this is working on my desktop, perhaps this is a problem with the specific device we were using this weekend. If I can replicate it I'll see about figuring out why and reopen this.
