### ISSUE TITLE
Adding treasures only possible for Gloomhaven, not JOTL

### ISSUE THREAD

**Issue by rbeumer** [Lurkars/gloomhavensecretary#32]
When I am trying to add treasures under the campaign sheet the only option seems to be 'Gloomhaven'. The party is using JOTL in the campaign mode but adding treasures by entering the number does not seem to be working and there is also no option for JOTL treasures.

**Comment by Lurkars** [comment]
Should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/12b8462ab7e9456610f52810d75a2a2d57b38b2a ([v0.21.7](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.21.7))

**Comment by rbeumer** [comment]
It's working, thanks!
