### ISSUE TITLE
Ooze card possible typo

### ISSUE THREAD

**Issue by justsomebugposter** [Lurkars/gloomhavensecretary#34]
Ooze card 695 incorrectly showing range 1.  It should be range +1 modifying base stats.  Attaching picture of GH Secretary and picture of card from TTTS mod.
![Screenshot 2022-11-05 235954](https://user-images.githubusercontent.com/117556316/200154059-35a244c2-b9ea-4762-af9e-ddb435703776.jpg)
![Screenshot 2022-11-05 235000](https://user-images.githubusercontent.com/117556316/200154074-cda2ef65-4769-4a29-936a-70188b91b22d.jpg)
P.S.  Thanks for all the great work

**Comment by Lurkars** [comment]
Thanks, fixed with https://github.com/Lurkars/gloomhavensecretary/commit/75d477c70b3396401421318ed03194339bf31966 ([v0.24.2](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.24.2))

**Comment by justsomebugposter** [comment]
Well that was fast.  Thanks much!
