### ISSUE TITLE
Attack modifier difficult to use on mobile

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretary#35]
My friends and I just started using your website in a campaign today. Awesome work!

we had one laptop as a larger display, and the mobile phones as extras to manage our own characters. We did struggle using the attack modifiers on mobile phones as the card is just too small to be accurate, and we generally fat fingered other actions. As a result, it became nearly impossible to purposefully click on either:

- the card itself the draw the next card
- the upper left zoom to go full screen
- the bottom right to modify  the deck

![image](https://user-images.githubusercontent.com/3196162/201512774-0574190a-6adb-4bb7-85c2-80ebe0cf8ec9.png)

My suggestion would be to modify touch behaviour when the card becomes 'too small' and maybe make use of different touch actions:

- tap to draw the card
- long tap to modify

or perhaps:

- tap to go full screen (and then we can draw)
- long tap to modify

**Comment by Lurkars** [comment]
I certainly tried to just fix this problem with the fullscreen mode. Maybe try vertical screen orientation? Else post maybe a full screenshot for me to better see the problem. I mostly tested also everything on mobile. Maybe also post device information like screen size.

**Comment by JP-Ellis** [comment]
Here's a screenshot of the whole page on my phone. I have a larger model, so mine was _just_ usable, but even at this resolution I often fat-fingered the attack modifier cards:

![signal-2022-11-14-080925](https://user-images.githubusercontent.com/3196162/201544717-3d954463-b7d0-44a7-a592-1d6ec2dfa8a8.png)

Increasing the zoom does fix this particular issue, but it then makes a lot of other elements in the interface quite clunky.

I was thinking about my suggestions above some more, and for mobiles devices it might be better to have the following:

- When clicking on the attack modifier round icon, go straight to opening the full-screen page for attack modifiers since on that page,  it is really easy to draw an attack modifier. This could be triggered by detecting the screen size/aspect ratio/device, and maybe could be a setting (i.e. always on, always off, autodetect)?
- On the full screen page, add a button on the page to go to the attack modifier deck editor
- On the full screen page, have the layout be responsive so that:
  - On wide screens, the layout remains as is with the draw pile to the left and cards are flipped to the right
  - On narrow/tall screens, the layout could have the draw pile at the top and cards are flipped down

**Comment by Lurkars** [comment]
with [v0.25.1](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.25.0), I added some improvements and hope they work out for you.
- on small device width or height, automatically open fullscreen deck (can be disabled in settings!)
- fullscreen mode now has a vertical mode
