### ISSUE TITLE
Increasing font size causes monster stats to shift

### ISSUE THREAD

**Issue by Infi220** [Lurkars/gloomhavensecretary#38]
When I increase font size then the monster default stats shift out of place to the right overlapping other info. I tested this in the web version on the desktop as well as an app version on Android. Both have the same problem.

![Annotation 2022-11-19 144356](https://user-images.githubusercontent.com/34073985/202874494-68f00124-e229-493d-8a92-ddf0814ee2eb.jpg)

**Comment by Lurkars** [comment]
Should be fixed with [v0.26.5](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.26.5). Please test and close issue if resolved.
