### ISSUE TITLE
Add a setting to enable/disable keyboard input of initiative

### ISSUE THREAD

**Issue by Infi220** [Lurkars/gloomhavensecretary#39]
Would it be possible to add a setting that enables/disables keyboard input of the initiative, so that when the user clicks the initiative number a dialog entry is shown instead of keyboard mode? I'm aware that clicking the small spot above the initiative number brings up the dialog but it's difficult to click such a tiny spot on a phone, and oftentimes when I try doing that the app thinks I clicked the number which brings up a large on-screen keyboard.
![Screenshot_20221119-145856](https://user-images.githubusercontent.com/34073985/202875005-5acb73e4-e947-4384-b40f-a8bca135c7ed.png)

**Comment by Lurkars** [comment]
Just click on the character image to open dialog!

**Comment by Infi220** [comment]
That works, thank you! Please, ignore my request then :)

**Comment by Lurkars** [comment]
Nevertheless due to your screenshot, I noticed, that you cannot open the initiative dialog during round, because image click toggles active state. So I will add a doubleclick action for this case to open dialog.

**Comment by Infi220** [comment]
I noticed that too but I think the player should not change the initiative during a round. In fact, GHH completely disables the initiative input dialog once the round starts. 

I played with GHS on my Pixel 4A a bit and I noticed that during the round whenever I click a character pic to end their turn, about 30% of the time the app thinks I clicked the initiative, so it brings up the keyboard or initiative dialog.  This is because clicks on a small touchscreen are imprecise. So, I think it would be best to disable the initiative input during the round.

**Comment by Lurkars** [comment]
On helper I can still drag initiative when round started. There may be some cases, where one wants to change after round started. Anyways most importantly regardless of what to think about that specific behaviour, if you have issues with single click vs double click on mobile, than I need to fix this. There are some more double click functions, so please open a general issue and I take a look.

**Comment by Infi220** [comment]
In my Android GHH app the actual initiative number can't be changed during the round. Only the order of the character mats can be dragged and moved around but the actual initiative number stays unchanged.

I tested the latest GHS and I have 2 observations:
- Double click works but it's very uncommon on phone apps. More common would be a long press
- I highly recommend at least adding a setting "No initiative change during a round". I keep getting the unwanted initiative dialog or keyboard popping up during the round very often when I just press the character picture trying to end their turn.

**Comment by Lurkars** [comment]
As already mentioned: I can change initiative in GHH during round by dragging initiative. Don't know if it's intended, but possible. Anyways, I think you're right, that it should be an exception and I will add a setting like "Enable initiative change during round" or so to explicit enable it.

The long press is a nice idea and will optimize feeling on mobile. Need to check a bit best way to implement, but will definetly take a look.

**Comment by Infi220** [comment]
Ok, thank you! Not sure why we are seeing different behavior in GHH. I'm using v.8.4.12 on Android Pixel 4A. GHH has a few settings for the initiative and I tried them all, but none allowed me to change the actual initiative number during the round (only the order of the character mats). Maybe GHH has a bug which results in a different behavior on your device and on my phone.

**Comment by Infi220** [comment]
I tried this on my phone and clicking the character pic seems broken now:
- before the round it no longer brings up initiative dialog
- during the round it no longer ends character's turn

**Comment by Lurkars** [comment]
I hate mobile. Tested on my android with 3 browsers and on desktop with mobile simulation. All fine... I will try something and update and hope it fixes.

**Comment by Lurkars** [comment]
Hopefully fixed, can you check again please?
