### ISSUE TITLE
Scenario Level 4 Living Bones mistake

### ISSUE THREAD

**Issue by smingerson** [Lurkars/gloomhavensecretary#4]
Great app! The Normal living bones should specify 1 shield but does not.

**Comment by Lurkars** [comment]
It does for me. Are you in level 0? Then it doesn't. 

Source: https://github.com/any2cards/gloomhaven/raw/master/images/monster-stat-cards/gloomhaven/gh-living-bones-0.png

GHS:
![IMG_20220705_161845.jpg](https://user-images.githubusercontent.com/2760570/177349567-846c0a8f-2ccc-4ad2-a4c6-24b1f4d915fe.jpg)

**Comment by smingerson** [comment]
Look at your screenshot -- it is present for other scenario levels but oddly skips 4.

**Comment by smingerson** [comment]
Sorry, had it in the title but not in the body of the message.

**Comment by Lurkars** [comment]
fixed in https://github.com/Lurkars/gloomhavensecretary/commit/c91a8cc8ebf433f692eb0aa73173e50baeaf98f2
