### ISSUE TITLE
Add flying indicator

### ISSUE THREAD

**Issue by smingerson** [Lurkars/gloomhavensecretary#6]
There is no indicator on monster cards for flying. Mentioning it here since I did not see it on BGG or GHS, even though you are already probably aware of it. Thank you again for the fantastic app and all your hard work!

**Comment by Lurkars** [comment]
Yes thanks. This wasn't actually in my mind, but I remember that I thought before I need to do it. Maybe I should keep a list of all features missing.  But yeah, I hope to close this issue today by just adding a flying indicator. 👍

**Comment by Lurkars** [comment]
Should be done with https://github.com/Lurkars/gloomhavensecretary/commit/9f46d9ec092fbfd271b1d97329aa8ee8d99c6e50
Besides flying wasn't shown, it wasn't even stored for the monsters. So this should now be available as icon on the stat card and all move actions have flying icon if monster has flying.
